[build]
builder = "nixpacks"
buildCommand = "npm ci && npm run build"
nixpacksVersion = "1.29.1"

[build.nixpacks]
providers = ["node"]

[build.nixpacks.apt]
pkgs = []

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
